package entity;
// Generated 2018-06-02 11:50:04 by Hibernate Tools 4.3.1



/**
 * DetaillivraisonId generated by hbm2java
 */
public class DetaillivraisonId  implements java.io.Serializable {


     private int nolivraison;
     private int nocommande;
     private int noarticle;

    public DetaillivraisonId() {
    }

    public DetaillivraisonId(int nolivraison, int nocommande, int noarticle) {
       this.nolivraison = nolivraison;
       this.nocommande = nocommande;
       this.noarticle = noarticle;
    }
   
    public int getNolivraison() {
        return this.nolivraison;
    }
    
    public void setNolivraison(int nolivraison) {
        this.nolivraison = nolivraison;
    }
    public int getNocommande() {
        return this.nocommande;
    }
    
    public void setNocommande(int nocommande) {
        this.nocommande = nocommande;
    }
    public int getNoarticle() {
        return this.noarticle;
    }
    
    public void setNoarticle(int noarticle) {
        this.noarticle = noarticle;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof DetaillivraisonId) ) return false;
		 DetaillivraisonId castOther = ( DetaillivraisonId ) other; 
         
		 return (this.getNolivraison()==castOther.getNolivraison())
 && (this.getNocommande()==castOther.getNocommande())
 && (this.getNoarticle()==castOther.getNoarticle());
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + this.getNolivraison();
         result = 37 * result + this.getNocommande();
         result = 37 * result + this.getNoarticle();
         return result;
   }   


}


