package entity;
// Generated 2018-06-02 11:50:04 by Hibernate Tools 4.3.1



/**
 * Detaillivraison generated by hbm2java
 */
public class Detaillivraison  implements java.io.Serializable {


     private DetaillivraisonId id;
     private Integer quantitylivree;

    public Detaillivraison() {
    }

	
    public Detaillivraison(DetaillivraisonId id) {
        this.id = id;
    }
    public Detaillivraison(DetaillivraisonId id, Integer quantitylivree) {
       this.id = id;
       this.quantitylivree = quantitylivree;
    }
   
    public DetaillivraisonId getId() {
        return this.id;
    }
    
    public void setId(DetaillivraisonId id) {
        this.id = id;
    }
    public Integer getQuantitylivree() {
        return this.quantitylivree;
    }
    
    public void setQuantitylivree(Integer quantitylivree) {
        this.quantitylivree = quantitylivree;
    }




}


