package entity;
// Generated 2018-06-06 08:39:38 by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import java.util.HashSet;
import java.util.Set;

/**
 * Editeur generated by hbm2java
 */
public class Editeur  implements java.io.Serializable {


     private BigDecimal idEditeur;
     private String nomEditeur;
     private String typeEditeur;
     private String paysEditeur;
     private Set livres = new HashSet(0);

    public Editeur() {
    }

	
    public Editeur(BigDecimal idEditeur, String nomEditeur, String typeEditeur, String paysEditeur) {
        this.idEditeur = idEditeur;
        this.nomEditeur = nomEditeur;
        this.typeEditeur = typeEditeur;
        this.paysEditeur = paysEditeur;
    }
    public Editeur(BigDecimal idEditeur, String nomEditeur, String typeEditeur, String paysEditeur, Set livres) {
       this.idEditeur = idEditeur;
       this.nomEditeur = nomEditeur;
       this.typeEditeur = typeEditeur;
       this.paysEditeur = paysEditeur;
       this.livres = livres;
    }
   
    public BigDecimal getIdEditeur() {
        return this.idEditeur;
    }
    
    public void setIdEditeur(BigDecimal idEditeur) {
        this.idEditeur = idEditeur;
    }
    public String getNomEditeur() {
        return this.nomEditeur;
    }
    
    public void setNomEditeur(String nomEditeur) {
        this.nomEditeur = nomEditeur;
    }
    public String getTypeEditeur() {
        return this.typeEditeur;
    }
    
    public void setTypeEditeur(String typeEditeur) {
        this.typeEditeur = typeEditeur;
    }
    public String getPaysEditeur() {
        return this.paysEditeur;
    }
    
    public void setPaysEditeur(String paysEditeur) {
        this.paysEditeur = paysEditeur;
    }
    public Set getLivres() {
        return this.livres;
    }
    
    public void setLivres(Set livres) {
        this.livres = livres;
    }




}


