package entity;
// Generated 2018-05-28 19:53:34 by Hibernate Tools 4.3.1



/**
 * Projet generated by hbm2java
 */
public class Projet  implements java.io.Serializable {


     private int numprojet;
     private String titre;
     private Integer numsuccursale;
     private Double budjet;

    public Projet() {
    }

	
    public Projet(int numprojet, String titre) {
        this.numprojet = numprojet;
        this.titre = titre;
    }
    public Projet(int numprojet, String titre, Integer numsuccursale, Double budjet) {
       this.numprojet = numprojet;
       this.titre = titre;
       this.numsuccursale = numsuccursale;
       this.budjet = budjet;
    }
   
    public int getNumprojet() {
        return this.numprojet;
    }
    
    public void setNumprojet(int numprojet) {
        this.numprojet = numprojet;
    }
    public String getTitre() {
        return this.titre;
    }
    
    public void setTitre(String titre) {
        this.titre = titre;
    }
    public Integer getNumsuccursale() {
        return this.numsuccursale;
    }
    
    public void setNumsuccursale(Integer numsuccursale) {
        this.numsuccursale = numsuccursale;
    }
    public Double getBudjet() {
        return this.budjet;
    }
    
    public void setBudjet(Double budjet) {
        this.budjet = budjet;
    }




}


