package entity;
// Generated 2018-05-28 19:53:34 by Hibernate Tools 4.3.1



/**
 * Succursale generated by hbm2java
 */
public class Succursale  implements java.io.Serializable {


     private int numsuccursale;
     private String designation;
     private String ville;
     private Double surface;
     private String capitale;

    public Succursale() {
    }

	
    public Succursale(int numsuccursale, String designation, String ville) {
        this.numsuccursale = numsuccursale;
        this.designation = designation;
        this.ville = ville;
    }
    public Succursale(int numsuccursale, String designation, String ville, Double surface, String capitale) {
       this.numsuccursale = numsuccursale;
       this.designation = designation;
       this.ville = ville;
       this.surface = surface;
       this.capitale = capitale;
    }
   
    public int getNumsuccursale() {
        return this.numsuccursale;
    }
    
    public void setNumsuccursale(int numsuccursale) {
        this.numsuccursale = numsuccursale;
    }
    public String getDesignation() {
        return this.designation;
    }
    
    public void setDesignation(String designation) {
        this.designation = designation;
    }
    public String getVille() {
        return this.ville;
    }
    
    public void setVille(String ville) {
        this.ville = ville;
    }
    public Double getSurface() {
        return this.surface;
    }
    
    public void setSurface(Double surface) {
        this.surface = surface;
    }
    public String getCapitale() {
        return this.capitale;
    }
    
    public void setCapitale(String capitale) {
        this.capitale = capitale;
    }




}


