package entity;
// Generated 2018-05-28 19:53:34 by Hibernate Tools 4.3.1



/**
 * Vendeur generated by hbm2java
 */
public class Vendeur  implements java.io.Serializable {


     private int numvendeur;
     private String nom;
     private String prenom;
     private String type;
     private String ville;
     private Integer numsuccursale;
     private Double salairefixe;
     private Double commision;

    public Vendeur() {
    }

	
    public Vendeur(int numvendeur, String nom, String prenom, String ville) {
        this.numvendeur = numvendeur;
        this.nom = nom;
        this.prenom = prenom;
        this.ville = ville;
    }
    public Vendeur(int numvendeur, String nom, String prenom, String type, String ville, Integer numsuccursale, Double salairefixe, Double commision) {
       this.numvendeur = numvendeur;
       this.nom = nom;
       this.prenom = prenom;
       this.type = type;
       this.ville = ville;
       this.numsuccursale = numsuccursale;
       this.salairefixe = salairefixe;
       this.commision = commision;
    }
   
    public int getNumvendeur() {
        return this.numvendeur;
    }
    
    public void setNumvendeur(int numvendeur) {
        this.numvendeur = numvendeur;
    }
    public String getNom() {
        return this.nom;
    }
    
    public void setNom(String nom) {
        this.nom = nom;
    }
    public String getPrenom() {
        return this.prenom;
    }
    
    public void setPrenom(String prenom) {
        this.prenom = prenom;
    }
    public String getType() {
        return this.type;
    }
    
    public void setType(String type) {
        this.type = type;
    }
    public String getVille() {
        return this.ville;
    }
    
    public void setVille(String ville) {
        this.ville = ville;
    }
    public Integer getNumsuccursale() {
        return this.numsuccursale;
    }
    
    public void setNumsuccursale(Integer numsuccursale) {
        this.numsuccursale = numsuccursale;
    }
    public Double getSalairefixe() {
        return this.salairefixe;
    }
    
    public void setSalairefixe(Double salairefixe) {
        this.salairefixe = salairefixe;
    }
    public Double getCommision() {
        return this.commision;
    }
    
    public void setCommision(Double commision) {
        this.commision = commision;
    }




}


