package entity;
// Generated 2018-05-28 19:53:34 by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * Vente generated by hbm2java
 */
public class Vente  implements java.io.Serializable {


     private VenteId id;
     private Integer quantite;
     private Date datevente;

    public Vente() {
    }

	
    public Vente(VenteId id, Date datevente) {
        this.id = id;
        this.datevente = datevente;
    }
    public Vente(VenteId id, Integer quantite, Date datevente) {
       this.id = id;
       this.quantite = quantite;
       this.datevente = datevente;
    }
   
    public VenteId getId() {
        return this.id;
    }
    
    public void setId(VenteId id) {
        this.id = id;
    }
    public Integer getQuantite() {
        return this.quantite;
    }
    
    public void setQuantite(Integer quantite) {
        this.quantite = quantite;
    }
    public Date getDatevente() {
        return this.datevente;
    }
    
    public void setDatevente(Date datevente) {
        this.datevente = datevente;
    }




}


