package entite;
// Generated 2018-05-16 08:54:42 by Hibernate Tools 4.3.1


import java.math.BigDecimal;

/**
 * Detaillivraison generated by hbm2java
 */
public class Detaillivraison  implements java.io.Serializable {


     private DetaillivraisonId id;
     private Livraison livraison;
     private BigDecimal quantitelivree;

    public Detaillivraison() {
    }

    public Detaillivraison(DetaillivraisonId id, Livraison livraison, BigDecimal quantitelivree) {
       this.id = id;
       this.livraison = livraison;
       this.quantitelivree = quantitelivree;
    }
   
    public DetaillivraisonId getId() {
        return this.id;
    }
    
    public void setId(DetaillivraisonId id) {
        this.id = id;
    }
    public Livraison getLivraison() {
        return this.livraison;
    }
    
    public void setLivraison(Livraison livraison) {
        this.livraison = livraison;
    }
    public BigDecimal getQuantitelivree() {
        return this.quantitelivree;
    }
    
    public void setQuantitelivree(BigDecimal quantitelivree) {
        this.quantitelivree = quantitelivree;
    }




}


